// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

var Generators = map[string]table.Generator{
	"projects": 	GetProjectTable,
	"tasks": 		GetTaskTable,
}
